### ISSUE TITLE
what should I change in code to fill username box with username?

### ISSUE THREAD

**Issue by usama7628674** [Dviros/CredsLeaker#6]
@Dviros User just have to type password only.

**Comment by Dviros** [comment]
Hey @usama7628674, it was possible in Powershell by using 
"-UserName $CurrentDomain_1"\"$username" (as can be seen here: https://github.com/Dviros/CredsLeaker/commit/2ec63008226f30e880dd25e6f4350fe09b45ff99 - line 27).
Since we're calling the Windows API, it's much more difficult. I think it's related to this: https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.ui.credentialpickeroptions.previouscredential#Windows_Security_Credentials_UI_CredentialPickerOptions_PreviousCredential

What do you think?

**Comment by usama7628674** [comment]
@Dviros The IBuffer in above link says

> Determines whether dialog box fields are filled with previous credentials. The default value is not to prepopulate the fields.

So it means we can't prepopulate the fields.I'll dig more and see what I can find.

**Comment by usama7628674** [comment]
@Dviros As an aside: In PowerShell, functions are invoked like shell commands - ```foo arg1 arg2``` - not like C# methods - ```foo(arg1, arg2)```; see [Get-Help about_Parsing](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing). If you use ```,``` to separate arguments, you'll construct an array that a function sees as a single argument. To prevent accidental use of method syntax, use [Set-StrictMode -Version 2](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode) or higher, but note its other effects.
The same applies to the ```New-Object``` calls: instead of ```New-Object SomeType(arg1, ...)```, use ```New-Object SomeType [-ArgumentList] arg1, ...```

**Comment by Dviros** [comment]
Thanks, fixed the function calls.
